New Getting Started Web SDK Starter Project
dolbyio-samples/comms-sdk-web-getting-started pull request #26
Opened 2022-06-21 15:50 UTC by j12y

This updated starter project demonstrates a Video Call between two participants.  For the previous version
of the getting started experience you can find it in the sdk3.5 branch for legacy tutorials.

Learn more:
https://docs.dolby.io/communications-apis/docs/getting-started-with-the-javascript-sdk

2022-06-21 16:01 UTC, FabienLavocat requested changes

2022-06-21 16:01 UTC, FabienLavocat commented on README.md
> +# Dolby.io Communications Web SDK
Can you please add "Getting Started" somewhere in the title?

2022-06-21 16:01 UTC, FabienLavocat commented on video-calls/util/dolbyio-auth-helper.js
> +dolbyio.getAccessToken = () => {
Can you please fix the indentation for this function.

2022-06-21 23:47 UTC, j12y commented on video-calls/util/dolbyio-auth-helper.js
> +dolbyio.getAccessToken = () => {
Some editor must be misbehaving, had a mix of tabs and spaces.

2022-06-23 16:21 UTC, FabienLavocat approved these changes

2022-06-23 16:23 UTC, merged